language: elixir
sudo: false

otp_release:
  - 21
elixir:
  - 1.9

matrix:
  include:
    - elixir: '1.4'
      otp_release: '19.3'
    - elixir: '1.5'
      otp_release: '19.3'
    - elixir: '1.5'
      otp_release: '20.3'
    - elixir: '1.6'
      otp_release: '19.3'
    - elixir: '1.6'
      otp_release: '20.3'
    - elixir: '1.7'
      otp_release: '19.3'
    - elixir: '1.7'
      otp_release: '20.3'
    - elixir: '1.7'
      otp_release: '21.3'
    - elixir: '1.7'
      otp_release: '22.0'
    - elixir: '1.8'
      otp_release: '20.3'
    - elixir: '1.8'
      otp_release: '21.3'
    - elixir: '1.8'
      otp_release: '22.0'
    - elixir: '1.9'
      otp_release: '20.3'
    - elixir: '1.9'
      otp_release: '21.3'
    - elixir: '1.9'
      otp_release: '22.0'
    - elixir: '1.10'
      otp_release: '20.3'
    - elixir: '1.10'
      otp_release: '21.3'
    - elixir: '1.10'
      otp_release: '22.0'

env:
  global:
    - MIX_ENV=test

cache:
  directories:
    - _build
    - deps
    - priv/plts

install:
  - mix local.rebar --force; mix local.hex --force; mix deps.get

script:
  - mix compile
  - mix credo --strict
  - mix dialyzer --halt-exit-status
  - mix test
  - mix coveralls.travis

#deploy:
#  provider: script
#  script: >-
#    mix deps.get &&
#    mix hex.config username "$HEX_USERNAME" &&
#    (mix hex.config encrypted_key "$HEX_ENCRYPTED_KEY" > /dev/null 2>&1) &&
#    (echo "$HEX_PASSPHRASE"\\nY | mix hex.publish) &&
#    mix clean &&
#    mix deps.clean --all
#  on:
#    tags: true
